Add progress check functionality
zippyvision/zippy-id-android-sdk pull request #5
Opened 2019-07-09 16:44 UTC by MelanijaGrunte

ZIPPY-20: Verifikācijas retry

Man nav pārliecības, cik pareizi esmu sapratusi prasības. Ja vajag, varēšu vēl pētīt un darīt.

2019-07-10 07:55 UTC, ULazdins reviewed
@mkims  uzmet, lūdzu, Tu arī šim aci :)

2019-07-10 07:55 UTC, ULazdins commented on zippy-droid/src/main/java/com/zippyid/zippydroid/wizard/ErrorFragment.kt
> +            (activity as? ZippyActivity)?.onRetryStep(documentType)
Būtu kruta, ja ErrorFragment nezinātu, ka fragmenta parent ir tieši ZippyActivity, bet tā vietā padotu kaut kādu vispārīgu callback, ko vecāks pats apstrādātu

2019-07-10 10:09 UTC, MelanijaGrunte commented
> @mkims uzmet, lūdzu, Tu arī šim aci :)

Pēc vivas refaktorēšanas, man šī struktūra vispār mulsina.. Varētu activity api(?) darbības pārcelt uz viewModel'i, ne @mkims ?

2019-07-10 10:10 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/ZippyActivity.kt
> +            error?.let { returnIntent.putExtra(ZIPPY_RESULT, error.localizedMessage) } ?: run {
```
error?.apply { 
       returnIntent.putExtra(ZIPPY_RESULT, error.localizedMessage)
} ?: returnIntent.putExtra(ZIPPY_RESULT, "Request timed out")
```

2019-07-10 10:10 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/ZippyActivity.kt
> +
Rindiņā

2019-07-10 10:10 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/ZippyActivity.kt
> +                    zippyResult.let { returnIntent.putExtra(ZIPPY_RESULT, it) }
`.apply`

2019-07-10 10:10 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/ZippyActivity.kt
> +        supportFragmentManager.beginTransaction().replace(R.id.fragment_container_fl, ErrorFragment.newInstance(verification, documentType)).commit()
Zippijā Navigatora vēl nav? :D

2019-07-10 10:10 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/wizard/ErrorFragment.kt
> +            (activity as? ZippyActivity)?.onRetryStep(documentType)
Jāuztaisa kopīgais ViewModelis, kuram ir metode `onRetryStep(documentType)`. Un lai ZippyActivity klausās uz rezultātiem

2019-07-10 10:10 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/wizard/ErrorFragment.kt
> +
Rindiņa

2019-07-10 10:10 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/wizard/WizardFragment.kt
> +                (activity as? ZippyActivity)?.state = ZippyActivity.ZippyState.READY
Atkāl būtu forši lai Wizardam ir kopīgs viewModelis ar ZippyActivity, kurš patur visus state

2019-07-10 10:12 UTC, mkims commented
> > @mkims uzmet, lūdzu, Tu arī šim aci :)
> 
> Pēc vivas refaktorēšanas, man šī struktūra vispār mulsina.. Varētu activity api(?) darbības pārcelt uz viewModel'i, ne @mkims ?

Tieši ta :P Vivas refaktorēšanas pievienotā vērtiba ftw! :D

2019-07-11 11:45 UTC, MelanijaGrunte commented
@ULazdins @mkims ir strādājoša jauna versija, bet domāju, ka pirms jūs skataties sīkumus, ko uzlabot, varbūt ir kādi vispārīgi ieteikumi.

2019-07-15 10:45 UTC, MelanijaGrunte commented
@mkims

2019-07-15 11:07 UTC, mkims requested changes

2019-07-15 11:07 UTC, mkims commented on zippy-droid/build.gradle
> +    implementation 'com.google.dagger:dagger-android:2.22.1'
Neredzu nekur appā daggeri :P

2019-07-15 11:07 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/ZippyActivity.kt
> +        error?.let { returnIntent.putExtra(ZIPPY_RESULT, error.localizedMessage) } ?: run {
Šados gadījumos prasās tomēr jaunā rindiņā to let

2019-07-15 11:07 UTC, mkims commented on zippy-droid-demo/build.gradle
> +    dataBinding.enabled = true
Šo jāpieraksta README

2019-07-15 11:07 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/camera/CameraFragment.kt
> +        mCameraSource!!.takePicture(null, callback) // kpc sis?!
Kas tas pa kommentāru? :D

2019-07-15 11:07 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/wizard/ErrorFragment.kt
> +        binding.descriptionTv.text = if (errorMessage != null) resources.getString(R.string.reason_for_failure, errorMessage) else resources.getString(R.string.reason_unknown)
Gara rindiņa, labāk ar newlines

2019-07-15 11:07 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/wizard/WizardFragment.kt
> +                (activity as ZippyActivity).sendSuccessfulResult(response)
Šo arī jāpārceļ uz viewmodeli

2019-07-15 11:07 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/wizard/WizardFragment.kt
> +                (activity as ZippyActivity).sendErrorResult("Unknown error")
Un šo

2019-07-15 11:07 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/wizard/WizardFragment.kt
> +            (activity as ZippyActivity).sendCancelledResult(it.second)
Ja mēs šo uzreiz padodām ZippyActivity, tad lai ZippyActivity pati klausas uz šo

2019-07-15 13:30 UTC, MelanijaGrunte commented on zippy-droid/build.gradle
> +    implementation 'com.google.dagger:dagger-android:2.22.1'
tas bija outdated (vecs komits) ☹️

2019-07-15 14:14 UTC, MelanijaGrunte commented
@mkims

2019-07-15 14:18 UTC, mkims approved these changes

2019-07-15 14:18 UTC, mkims commented on README.md
> +enable data binding like so:
šis arī ir "in your app's build gradle" :D

2019-07-15 14:18 UTC, mkims commented on zippy-droid/src/main/java/com/zippyid/zippydroid/ZippyActivity.kt
> +        this.observeLiveData(viewModel.sendSuccessfulResultLiveData) {
Smuki :)

2019-07-15 14:39 UTC, merged